-- Carga inicial: el inventario actual de la web (fotos servidas desde /public/watches)
insert into watches (slug, status, brand, model, reference, year, has_box, has_papers, price, currency, case_size, material, dial, bracelet, description, movement, power_reserve, water_resistance, images, source, published_at) values
  ('rolex-daytona-126519ln-meteorite', 'available', 'Rolex', 'Cosmograph Daytona', '126519LN', null, true, true, null, 'USD', '40 mm', '{"en": "18k white gold", "es": "Oro blanco 18k"}'::jsonb, '{"en": "Meteorite, black sub-dials", "es": "Meteorito, subesferas negras"}'::jsonb, '{"en": "Oysterflex", "es": "Oysterflex"}'::jsonb, '{"en": "The Cosmograph Daytona in 18k white gold, paired with a meteorite dial — each one cut from a real meteorite, so no two are alike. Black sub-dials and a black Cerachrom bezel give it a sharp, high-contrast read, while the Oysterflex bracelet keeps it light and comfortable. Powered by calibre 4131. Complete with box and warranty card.", "es": "El Cosmograph Daytona en oro blanco de 18k con esfera de meteorito: cada esfera se corta de un meteorito real, así que no hay dos iguales. Las subesferas negras y el bisel Cerachrom negro le dan un contraste nítido, y el brazalete Oysterflex lo mantiene ligero y cómodo. Calibre 4131. Completo con caja y tarjeta de garantía."}'::jsonb, 'Rolex 4131', '72 h', '100 m', array['/watches/rolex-daytona-126519ln-box.jpg','/watches/rolex-daytona-126519ln.jpg']::text[], 'seed', now() - interval '0 minutes'),
  ('audemars-piguet-royal-oak-chronograph-26240st-green', 'available', 'Audemars Piguet', 'Royal Oak Chronograph', '26240ST', null, true, true, null, 'USD', '41 mm', '{"en": "Stainless steel", "es": "Acero inoxidable"}'::jsonb, '{"en": "Green “Grande Tapisserie”", "es": "Verde “Grande Tapisserie”"}'::jsonb, '{"en": "Integrated steel bracelet", "es": "Brazalete integrado de acero"}'::jsonb, '{"en": "The current-generation Royal Oak Chronograph in steel, with a green “Grande Tapisserie” dial and tone-on-tone sub-dials. The octagonal bezel, eight hexagonal screws and integrated bracelet are finished with the alternating brushed and polished surfaces Audemars Piguet is known for. In-house column-wheel calibre 4401 with flyback function.", "es": "El Royal Oak Chronograph de generación actual en acero, con esfera verde “Grande Tapisserie” y subesferas a juego. El bisel octogonal, sus ocho tornillos hexagonales y el brazalete integrado alternan superficies satinadas y pulidas, el sello de Audemars Piguet. Calibre de manufactura 4401 con rueda de pilares y función flyback."}'::jsonb, 'Audemars Piguet 4401', '70 h', '50 m', array['/watches/ap-royal-oak-chronograph-26240st.jpg']::text[], 'seed', now() - interval '1 minutes'),
  ('rolex-land-dweller-127235', 'available', 'Rolex', 'Land-Dweller 40', '127235', null, true, true, null, 'USD', '40 mm', '{"en": "18k Everose gold", "es": "Oro Everose 18k"}'::jsonb, '{"en": "White, honeycomb motif", "es": "Blanca, motivo de panal"}'::jsonb, '{"en": "Flat Jubilee, integrated", "es": "Flat Jubilee integrado"}'::jsonb, '{"en": "Rolex''s newest collection, in 18k Everose gold. The Land-Dweller pairs a fluted bezel with an integrated Flat Jubilee bracelet, and a white dial engraved with a honeycomb pattern. Inside is calibre 7135 with the Dynapulse escapement, beating at 5 Hz — a first for Rolex.", "es": "La colección más reciente de Rolex, en oro Everose de 18k. El Land-Dweller combina un bisel estriado con un brazalete Flat Jubilee integrado y una esfera blanca grabada con motivo de panal. En su interior, el calibre 7135 con escape Dynapulse que late a 5 Hz, una novedad en Rolex."}'::jsonb, 'Rolex 7135', '66 h', '100 m', array['/watches/rolex-land-dweller-127235.jpg']::text[], 'seed', now() - interval '2 minutes'),
  ('audemars-piguet-royal-oak-offshore', 'available', 'Audemars Piguet', 'Royal Oak Offshore Chronograph', '26420SO.OO.A600CA.01', null, true, true, 100000, 'USD', '43 mm', '{"en": "Steel & ceramic", "es": "Acero y cerámica"}'::jsonb, null, null, null, 'Audemars Piguet 4401', null, '100 m', '{}'::text[], 'seed', now() - interval '3 minutes'),
  ('rolex-yacht-master-40-everose', 'available', 'Rolex', 'Yacht-Master 40', '126711CHNR', null, true, true, 19500, 'USD', '40 mm', '{"en": "Everose Rolesor", "es": "Everose Rolesor"}'::jsonb, null, null, null, null, null, null, '{}'::text[], 'seed', now() - interval '4 minutes'),
  ('rolex-sky-dweller-336934', 'available', 'Rolex', 'Sky-Dweller', '336934', null, true, true, 18800, 'USD', '42 mm', '{"en": "Oystersteel & white gold", "es": "Acero Oystersteel y oro blanco"}'::jsonb, null, null, null, 'Rolex 9002', '72 h', '100 m', '{}'::text[], 'seed', now() - interval '5 minutes'),
  ('cartier-ballon-bleu', 'reserved', 'Cartier', 'Ballon Bleu', 'WSBB0040', null, true, false, 22000, 'USD', '42 mm', '{"en": "Steel", "es": "Acero"}'::jsonb, null, null, null, null, null, null, '{}'::text[], 'seed', now() - interval '6 minutes'),
  ('rolex-datejust-36', 'available', 'Rolex', 'Datejust 36', '126233', null, true, true, 17500, 'USD', '36 mm', '{"en": "Yellow Rolesor", "es": "Rolesor amarillo"}'::jsonb, null, null, null, 'Rolex 3235', '70 h', '100 m', '{}'::text[], 'seed', now() - interval '7 minutes'),
  ('rolex-lady-datejust-26-silver', 'available', 'Rolex', 'Lady-Datejust 26', '179174', null, false, false, 8500, 'USD', '26 mm', '{"en": "White Rolesor", "es": "Rolesor blanco"}'::jsonb, null, null, null, null, null, null, '{}'::text[], 'seed', now() - interval '8 minutes')
on conflict (slug) do nothing;
